name: Auto Pull Request

on:
  schedule:
    - cron: "0 * * * *" # Exécuter toutes les heures (HH:00)
  workflow_dispatch: # Permet un lancement manuel

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Modifier un fichier (exemple)
        run: |
          echo "Mise à jour automatique $(date)" >> update.log
          git add update.log
          git commit -m "Mise à jour automatique : $(date)" || echo "Aucun changement à commit"

      - name: Push vers une nouvelle branche
        run: |
          BRANCH_NAME="auto-update-$(date +'%Y-%m-%d-%H%M%S')"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Créer une Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: main
          title: "Mise à jour automatique : $(date)"
          body: "Cette pull request a été générée automatiquement via GitHub Actions."
          labels: "automated pr"
