name: Update README

on:
  schedule:
    - cron: '0 */1 * * *'  # Exécute toutes les 1 heure
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Donne les permissions nécessaires pour effectuer des commits
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "Last updated: $(date)" > README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README'
          git push
